### ISSUE TITLE
[BUG] Address in mailbox given [email] does not comply with RFC 2822

### ISSUE THREAD

**Issue by zomars** [bolt/boltforms#182]
https://github.com/bolt/boltforms/blob/890730429b158edf2d16d682604d2aca5b00f6c1/config/config.yml.dist#L106

As the docs say, when using this option to be one of the field values 'email', even if the email is valid Swiftmailer complains. Only when I put the same address in `from_email` it sends the message.

**Comment by rossriley** [comment]
This one was just fixed in v4.1.6

**Comment by dig412** [comment]
I'm still getting this in v4.1.6. It seems that `setEmailConfig` might not be doing the right thing.

It calls `getConfigValue`, and gets the correct value from the submitted form, but then tries to get a key of that name from the form data again, so e.g. it looks for a field called "myemail@example.org", which returns NULL, so it then falls back to the original config value.

**Comment by nestordedios** [comment]
Hi @rossriley !!
I'm bumping into the same issue here. It seems that the `$value` passed in `getConfigValue(Entity\Entity $formData, $value)` in the body of the `setEmailConfig()` https://github.com/bolt/boltforms/blob/4.1/src/Config/EmailConfig.php#L319 won't evalaute true when checking `instanceof FieldOptionsBag`  here https://github.com/bolt/boltforms/blob/4.1/src/Config/EmailConfig.php#L341.

Would this be difficult to fix? By the way thank you for the fixes added on v4.1.6 👍

**Comment by dig412** [comment]
Thanks @rossriley, 4.1.9 works perfectly.

**Comment by nestordedios** [comment]
Thanks @rossriley 👍 This worked for me too!
